# Generated by Django 5.2.13 on 2026-05-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0148_auto_20260427_2233"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0015_alter_userprofile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomValidation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entries",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the BOM entries at the time of validation",
                        null=True,
                        verbose_name="BOM entries",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Stored BOM checksum",
                        max_length=128,
                        verbose_name="BOM checksum",
                    ),
                ),
                (
                    "checked_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="BOM checked date"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_validations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="BOM checked by",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="Part assembly for this BOM validation entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_validations",
                        to="part.part",
                        verbose_name="Part",
                    ),
                ),
            ],
        ),
    ]
