# Generated by Django 5.2.13 on 2026-05-04 11:53

from django.db import migrations


def migrate_bom_validations(apps, schema_editor):
    """Migrate existing BomValidation entries.
    
    For each part which has existing BOM validation data,
    create a new BOMValidation entry with the existing data.
    """

    Part = apps.get_model("part", "Part")
    BomValidation = apps.get_model("part", "BomValidation")

    validations = []

    for part in Part.objects.all().exclude(bom_checked_date__isnull=True):

        validations.append(
            BomValidation(
                part=part,
                entries=None,
                checksum=part.bom_checksum,
                checked_date=part.bom_checked_date,
                checked_by_id=part.bom_checked_by_id,
            )
        )

    if len(validations) > 0:
        
        print(f"Migrating {len(validations)} existing BOM validation records.")

        BomValidation.objects.bulk_create(validations, batch_size=250)


def reverse_migrate_bom_validations(apps, schema_editor):
    """Reverse the migration of BOM validation data.
    
    This will not delete any BomValidation entries, but will clear the BOM validation data from the Part model.
    """

    Part = apps.get_model("part", "Part")
    BomValidation = apps.get_model("part", "BomValidation")

    part_ids = set()

    for validation in BomValidation.objects.all().order_by("-pk"):
        part = validation.part
        if part.pk in part_ids:
            continue

        part_ids.add(part.pk)

        part.bom_checksum = validation.checksum
        part.bom_checked_date = validation.checked_date
        part.bom_checked_by_id = validation.checked_by_id
        part.save()

    if len(part_ids) > 0:
        print(f"Reversed migration of BOM validation data for {len(part_ids)} parts.")

class Migration(migrations.Migration):

    dependencies = [
        ("part", "0149_bomvalidation"),
    ]

    operations = [
        migrations.RunPython(
            migrate_bom_validations,
            reverse_code=reverse_migrate_bom_validations,
        )
    ]
