# Generated by Django 5.2.13 on 2026-05-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0150_auto_20260504_1153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="bom_checked_by",
        ),
        migrations.RemoveField(
            model_name="part",
            name="bom_checked_date",
        ),
        migrations.RemoveField(
            model_name="part",
            name="bom_checksum",
        ),
    ]
